project:
  type: book
  preview:
    port: 4201
    browser: true
  render:
  - '*.md'
  - '*.qmd'
  - '!LICENSE.md'
  - '!README.md'
  output-dir: output/report_example
  post-render: _extensions/inbo/flandersqmd-book/filters/post_render.R
execute:
  echo: false
  warnings: true
  errors: true
  message: true
  freeze: false
  cache: false
format:
  flandersqmd-book-html: default
  flandersqmd-book-pdf: default
lang: en-GB
flandersqmd:
  entity: INBO
  level: 2
  title: Example report
  shorttitle: report-example
  author:
  - name:
      given: Jane
      family: Doe
    email: jane.doe@mail.com
    orcid: 0000-0002-1825-0097
    affiliation:
    - None
    corresponding: true
  reviewer:
  - name:
      given: John
      family: Doe
    email: john.doe@mail.com
    orcid: 0000-0002-1825-0097
    affiliation:
    - None
  rightsholder:
  - name:
      given: Research Institute for Nature and Forest (INBO)
    email: info@inbo.be
    ror: 00j54wy13
  funder:
  - name:
      given: Research Institute for Nature and Forest (INBO)
    email: info@inbo.be
    ror: 00j54wy13
  community: inbo
  public_report: true
  colophon: true
  floatbarrier: section
book:
  downloads: pdf
  open-graph: true
  body-footer: '{{< footer >}}'
  navbar:
    pinned: true
    right:
    - icon: mastodon
      href: https://mastodon.online/&#64;inbo
    - icon: facebook
      href: https://www.facebook.com/INBOVlaanderen/
    left:
    - text: Cover
      file: index.md
    - text: Recommendations
      file: recommendations.md
    - text: Introduction
      file: introduction.md
  chapters:
  - index.md
  - samenvatting.md
  - recommendations.md
  - introduction.md
  - bibliography.md
bibliography: references.bib
